REM Batch clip for SoCo LAS files. To avoid memory errors, the number of files per process is limited to 65. 

SET PROCESSINGHOME=C:\FUSION
REM shapefile name
SET POLYFILE=soco_lidar_clip.shp
REM folder to save the clipped lidar files
SET CLIPFOLDER=C:\Capstone\Data\LiDAR\SonomaCounty\LAS\clip
REM basename for clipped lidar files
SET CLIPNAME=slo_clip
REM basename of the text file containing the list of paths to the original lidar files to be clipped
SET LAZLIST=SoCoLAZs_

cd %PROCESSINGHOME%

PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_65.laz %PROCESSINGHOME%\%LAZLIST%65.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_130.laz %PROCESSINGHOME%\%LAZLIST%130.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_195.laz %PROCESSINGHOME%\%LAZLIST%195.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_260.laz %PROCESSINGHOME%\%LAZLIST%260.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_325.laz %PROCESSINGHOME%\%LAZLIST%325.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_390.laz %PROCESSINGHOME%\%LAZLIST%390.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_455.laz %PROCESSINGHOME%\%LAZLIST%455.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_520.laz %PROCESSINGHOME%\%LAZLIST%520.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_585.laz %PROCESSINGHOME%\%LAZLIST%585.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_650.laz %PROCESSINGHOME%\%LAZLIST%650.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_715.laz %PROCESSINGHOME%\%LAZLIST%715.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_780.laz %PROCESSINGHOME%\%LAZLIST%780.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_845.laz %PROCESSINGHOME%\%LAZLIST%845.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_910.laz %PROCESSINGHOME%\%LAZLIST%910.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_975.laz %PROCESSINGHOME%\%LAZLIST%975.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_1040.laz %PROCESSINGHOME%\%LAZLIST%1040.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_1105.laz %PROCESSINGHOME%\%LAZLIST%1105.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_1170.laz %PROCESSINGHOME%\%LAZLIST%1170.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_1235.laz %PROCESSINGHOME%\%LAZLIST%1235.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_1300.laz %PROCESSINGHOME%\%LAZLIST%1300.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_1365.laz %PROCESSINGHOME%\%LAZLIST%1365.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_1430.laz %PROCESSINGHOME%\%LAZLIST%1430.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_1495.laz %PROCESSINGHOME%\%LAZLIST%1495.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_1560.laz %PROCESSINGHOME%\%LAZLIST%1560.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_1625.laz %PROCESSINGHOME%\%LAZLIST%1625.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_1690.laz %PROCESSINGHOME%\%LAZLIST%1690.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_1755.laz %PROCESSINGHOME%\%LAZLIST%1755.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_1820.laz %PROCESSINGHOME%\%LAZLIST%1820.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_1885.laz %PROCESSINGHOME%\%LAZLIST%1885.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_1950.laz %PROCESSINGHOME%\%LAZLIST%1950.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_2015.laz %PROCESSINGHOME%\%LAZLIST%2015.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_2080.laz %PROCESSINGHOME%\%LAZLIST%2080.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_2145.laz %PROCESSINGHOME%\%LAZLIST%2145.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_2210.laz %PROCESSINGHOME%\%LAZLIST%2210.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_2275.laz %PROCESSINGHOME%\%LAZLIST%2275.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_2340.laz %PROCESSINGHOME%\%LAZLIST%2340.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_2405.laz %PROCESSINGHOME%\%LAZLIST%2405.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_2470.laz %PROCESSINGHOME%\%LAZLIST%2470.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_2535.laz %PROCESSINGHOME%\%LAZLIST%2535.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_2600.laz %PROCESSINGHOME%\%LAZLIST%2600.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_2665.laz %PROCESSINGHOME%\%LAZLIST%2665.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_2730.laz %PROCESSINGHOME%\%LAZLIST%2730.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_2795.laz %PROCESSINGHOME%\%LAZLIST%2795.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_2860.laz %PROCESSINGHOME%\%LAZLIST%2860.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_2925.laz %PROCESSINGHOME%\%LAZLIST%2925.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_2990.laz %PROCESSINGHOME%\%LAZLIST%2990.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_3055.laz %PROCESSINGHOME%\%LAZLIST%3055.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_3120.laz %PROCESSINGHOME%\%LAZLIST%3120.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_3185.laz %PROCESSINGHOME%\%LAZLIST%3185.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_3250.laz %PROCESSINGHOME%\%LAZLIST%3250.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_3315.laz %PROCESSINGHOME%\%LAZLIST%3315.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_3380.laz %PROCESSINGHOME%\%LAZLIST%3380.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_3445.laz %PROCESSINGHOME%\%LAZLIST%3445.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_3510.laz %PROCESSINGHOME%\%LAZLIST%3510.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_3575.laz %PROCESSINGHOME%\%LAZLIST%3575.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_3640.laz %PROCESSINGHOME%\%LAZLIST%3640.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_3705.laz %PROCESSINGHOME%\%LAZLIST%3705.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_3770.laz %PROCESSINGHOME%\%LAZLIST%3770.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_3835.laz %PROCESSINGHOME%\%LAZLIST%3835.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_3900.laz %PROCESSINGHOME%\%LAZLIST%3900.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_3965.laz %PROCESSINGHOME%\%LAZLIST%3965.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_4030.laz %PROCESSINGHOME%\%LAZLIST%4030.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_4095.laz %PROCESSINGHOME%\%LAZLIST%4095.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_4160.laz %PROCESSINGHOME%\%LAZLIST%4160.txt
PolyClipData /multifile %PROCESSINGHOME%\%POLYFILE% %CLIPFOLDER%\%CLIPNAME%_4173.laz %PROCESSINGHOME%\%LAZLIST%4173.txt


